---
title: "R for Data Science"
subtitle: "Chapter 10 : Data Import"
author: "Shamsuddeen Muhammad (@shmuhammadd)"
Date :  "`r Sys.Date()` "
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: xaringan-themer.css
    includes:
      after_body: insert-logo.html
---


```{r xaringan-themer, include = FALSE, warning=FALSE}
library(xaringanthemer)
mono_light(
  base_color = "#3092FF",
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "300", "300i"),
  code_font_google   = google_font("Droid Mono"),
)

library(tidyverse)
```



# What's in Chapter 10:

--

- Section 11.2: Most of common readr’s function 

--

- Section 11.3: Parsing a vector

--

- Section 11.4: Parsing a file

--

- Section 11.5: Writting to a file
--

- Section 11.5: Other types of data


---


# Section 11.2: readr’s function:


-  Developed by Hadley Wickham to deal with reading in large flat files quickly. 

- provides replacements for base R functions like `read.table()` and `read.csv()`. 

- The analogous functions in readr are `read_table()` and `read_csv()` : they are faster and provide a few other nice features such as progress meters.
 
   `read_csv()` reads comma delimited files.
  
   `read_csv2()` reads semicolon separated files.
  
   `read_tsv()` reads tab delimited files, 
  
   `read_delim()` reads in files with any delimiter (Demo).


---


# Section 11.2: read_csv vs read.csv 


- `read_csv` are faster than read.csv, but slower than data.table::fread()(does not works well with tidyverse).

- `read_csv` produce tibble, never `convert character vectors to factors`, use `row names or munge the column names`.

-  more reproducible. Base R functions might not work on someone else’s system.
---


---


#  1.3 Parsing a vector

- The key problem that `readr` solves is parsing a `flat file` into a tibble

- Parsing is the `process of taking a text file and turning it into a rectangular tibble`  where each column is the appropriate part.


- 3 ways  `readr` solves probelm of parsing: 
  - `Vector parsers` turn a character vector in to a more specific typ
  - `Column specification` describes the type of each column and the strategy readr uses to guess types so you don’t need to supply them all
  
  - `Rectangular parsers` turn a flat file into a matrix of rows and columns.




---




---


#  1.3 Parsing a Vector

- `parse_*()` takes a character vector and return a more specialised vector like a `logical`, `integer`, or `date`


- There are eight particularly important parsers.(Demo) 


- `perse_*()` functions  are useful in their own right, but are also an important building block for `readr`

---



#   Numbers 

- People write numbers differently in different parts of the world.

 - Some use . and , to separate number
 -  Sometimes number are written with character attached (e.g $100, 100%) 
 - grouping characters to make them easier to read, such “1,000,000” (also grouping characters vary around the world)



- `reader` uses an option `locale` to solve the address the first problem, 
- `readr` uses parse_number() to addresses the second problem

-  `readr` uses   combination of  `parse_number()` and the locale as `parse_number()

- Demo

---


#  Others

- Strings
- Factors
- Dates, date-times, and times 

---

---


#   Parsing a file{-} (Column specification)

- Strategy
- Problems
- Other strategies

---



---


#  Writting to a file

- Strategy
- Problems
- Other strategies

---






class: inverse, hide-logo
